export const initialMovies = [
  {
    id: "1",
    title: "Spider-Man: Across the Spider-Verse",
    originalTitle: "Spider-Man: Across the Spider-Verse",
    type: "pelicula",
    year: 2023,
    duration: 140,
    rating: 8.7,
    genres: ["Animación", "Acción", "Ciencia Ficción"],
    director: "Joaquim Dos Santos, Kemp Powers",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Daniel Kaluuya"],
    status: "Disponible",
    featured: true,
    poster: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    trailerYoutubeId: "cqGjhVJWtEg",
    synopsis: "Miles Morales es catapultado a través del Multiverso, donde se encuentra con un equipo de Spider-People encargados de proteger su existencia. Sin embargo, cuando los héroes chocan sobre cómo manejar una nueva amenaza, Miles debe redefinir lo que significa ser un héroe.",
    voteCount: 14200,
    language: "Español / Inglés",
    createdAt: new Date().toISOString()
  },
  {
    id: "2",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    type: "pelicula",
    year: 2023,
    duration: 180,
    rating: 8.9,
    genres: ["Drama", "Historia", "Biografía"],
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    status: "Disponible",
    featured: true,
    poster: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
    trailerYoutubeId: "uYPbbksJxIg",
    synopsis: "La historia del científico estadounidense J. Robert Oppenheimer y su rol crucial en el desarrollo de la bomba atómica durante la Segunda Guerra Mundial a través del Proyecto Manhattan.",
    voteCount: 18900,
    language: "Inglés con subtítulos",
    createdAt: new Date().toISOString()
  },
  {
    id: "3",
    title: "Stranger Things (Temporada Final)",
    originalTitle: "Stranger Things 5",
    type: "serie",
    year: 2025,
    duration: 55,
    rating: 8.8,
    genres: ["Ciencia Ficción", "Terror", "Drama"],
    director: "The Duffer Brothers",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
    status: "Próximamente",
    featured: true,
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=yQEondeGvKo",
    trailerYoutubeId: "yQEondeGvKo",
    synopsis: "Hawkins se enfrenta a su mayor amenaza mientras la grieta hacia el Mundo del Revés se expande por completo. Eleven y sus amigos deberán unir fuerzas para la batalla final contra Vecna.",
    voteCount: 22400,
    language: "Español Latino",
    createdAt: new Date().toISOString()
  },
  {
    id: "4",
    title: "Dune: Parte Dos",
    originalTitle: "Dune: Part Two",
    type: "pelicula",
    year: 2024,
    duration: 166,
    rating: 8.6,
    genres: ["Ciencia Ficción", "Aventura", "Acción"],
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    status: "Disponible",
    featured: false,
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    trailerYoutubeId: "Way9Dexny3w",
    synopsis: "Paul Atreides se une a Chani y a los Fremen mientras busca venganza contra los conspiradores que destruyeron a su familia, enfrentando una encrucijada entre el amor de su vida y el destino del universo.",
    voteCount: 15300,
    language: "Español / Inglés",
    createdAt: new Date().toISOString()
  },
  {
    id: "5",
    title: "Arcane: League of Legends",
    originalTitle: "Arcane",
    type: "serie",
    year: 2024,
    duration: 45,
    rating: 9.0,
    genres: ["Animación", "Acción", "Fantasía"],
    director: "Christian Linke, Alex Yee",
    cast: ["Hailee Steinfeld", "Ella Purnell", "Kevin Alejandro", "Katie Leung"],
    status: "Disponible",
    featured: false,
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=fXmAurh012s",
    trailerYoutubeId: "fXmAurh012s",
    synopsis: "En medio del conflicto entre las ciudades gemelas de Piltover y Zaun, dos hermanas luchan en bandos opuestos de una guerra tecnológica entre magia y armas químicas.",
    voteCount: 19800,
    language: "Español Latino",
    createdAt: new Date().toISOString()
  },
  {
    id: "6",
    title: "The Batman",
    originalTitle: "The Batman",
    type: "pelicula",
    year: 2022,
    duration: 176,
    rating: 7.9,
    genres: ["Crimen", "Misterio", "Acción"],
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Colin Farrell"],
    status: "Disponible",
    featured: false,
    poster: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    trailerYoutubeId: "mqqft2x_Aa4",
    synopsis: "En su segundo año luchando contra el crimen, Batman explora la corrupción existente en Gotham City y el vínculo de esta con su propia familia mientras persigue al Asertijo.",
    voteCount: 12500,
    language: "Español / Inglés",
    createdAt: new Date().toISOString()
  },
  {
    id: "7",
    title: "The Last of Us",
    originalTitle: "The Last of Us",
    type: "serie",
    year: 2023,
    duration: 60,
    rating: 8.8,
    genres: ["Drama", "Terror", "Aventura"],
    director: "Craig Mazin, Neil Druckmann",
    cast: ["Pedro Pascal", "Bella Ramsey", "Gabriel Luna", "Anna Torv"],
    status: "Disponible",
    featured: false,
    poster: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=uLtkt8BonwM",
    trailerYoutubeId: "uLtkt8BonwM",
    synopsis: "20 años después de que una infección por hongos destruyera la civilización, Joel es contratado para sacar de contrabando a Ellie, una niña de 14 años que podría ser la clave para una cura.",
    voteCount: 16700,
    language: "Español Latino",
    createdAt: new Date().toISOString()
  },
  {
    id: "8",
    title: "Interstellar",
    originalTitle: "Interstellar",
    type: "pelicula",
    year: 2014,
    duration: 169,
    rating: 8.7,
    genres: ["Ciencia Ficción", "Drama", "Aventura"],
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    status: "Disponible",
    featured: false,
    poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    trailerYoutubeId: "zSWdZVtXT7E",
    synopsis: "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento por garantizar la supervivencia de la humanidad ante el colapso de la Tierra.",
    voteCount: 26000,
    language: "Español / Inglés",
    createdAt: new Date().toISOString()
  }
];

export const ALL_GENRES = [
  "Acción",
  "Aventura",
  "Animación",
  "Ciencia Ficción",
  "Comedia",
  "Crimen",
  "Drama",
  "Fantasía",
  "Historia",
  "Misterio",
  "Romance",
  "Terror",
  "Biografía"
];

export const SAMPLE_PRESETS = [
  {
    title: "Cyberpunk: Edgerunners",
    type: "serie",
    year: 2022,
    duration: 25,
    rating: 8.3,
    genres: ["Animación", "Acción", "Ciencia Ficción"],
    director: "Hiroyuki Imaishi",
    cast: ["Aoi Yuuki", "KENN", "Hiroki Touchi"],
    status: "Disponible",
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=JtqIas3bYhg",
    synopsis: "Un chico de la calle que intenta sobrevivir en Night City, una ciudad del futuro obsesionada con la tecnología y la modificación corporal, decide convertirse en un Edgerunner.",
    language: "Japonés / Español"
  },
  {
    title: "Gladiador II",
    type: "pelicula",
    year: 2024,
    duration: 148,
    rating: 7.8,
    genres: ["Acción", "Aventura", "Drama"],
    director: "Ridley Scott",
    cast: ["Paul Mescal", "Pedro Pascal", "Denzel Washington"],
    status: "Estreno",
    poster: "https://images.unsplash.com/photo-1533619043865-1c2e2f32ff2f?auto=format&fit=crop&w=800&q=80",
    backdrop: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1600&q=80",
    trailerUrl: "https://www.youtube.com/watch?v=4rgYUipGJNo",
    synopsis: "Años después de presenciar la muerte del venerado héroe Máximo a manos de su tío, Lucio debe entrar en el Coliseo tras ser conquistado su hogar por los tiránicos emperadores que ahora dirigen Roma.",
    language: "Español Latino"
  }
];
